### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by egalpin**
Added recipe for apt-vim to README

### CODE REVIEW

**Comment by marijnh** [comment]
Is the idea that people copy-paste the JSON chunk into their shell? Isn't there a more elegant way?

**Comment by egalpin** [comment]
There are a couple of alternatives, yes. I selected the copy/paste to terminal because I thought it was least error-prone method of the options I had considered. I agree with you that it reveals all of the ugliness to the user, which is unfortunate.

One alternative would require a slight extension of [apt-vim](https://github.com/egalpin/apt-vim) to support individual package installation from JSON.  This would allow for a method by which to hide the ugliness of the recipes.  For example, the JSON I added to the README could be stored in a JSON file in your (or other Vim plugins) repo root like so:
```json
@vimpkg
{
    "depends-on": [
        {
            "name": "node",
            "recipe": {
                "darwin": [
                    "brew install node"
                ],
                "linux": [
                    "sudo apt-get install -y node npm"
                ]
            }
        }
    ],
    "name": "tern_for_vim",
    "pkg-url": "https://github.com/marijnh/tern_for_vim.git",
    "recipe": {
        "all": [
            "npm install"
        ]
    }
}

```

Then, when a user runs `apt-vim install` from the cloned directory, the package could be picked up by automatically based on JSON files with `@vimpkg` and running context (i.e. executing `apt-vim` from the cloned directory).

I'm very open to input :-)

**Comment by marijnh** [comment]
The apt-vim docs talk about installing from urls. Can we set up something to allow that instead?

**Comment by egalpin** [comment]
Yes, I think I can set it up to automagically check for installation recipes before asking the user to input a recipe. I'll update you when I have something working. Thanks :-)

**Comment by egalpin** [comment]
Thanks a bunch for a push in the right direction! Now, config's for individual plugins can be stored in the repo itself (see the `vim_config.json` that I added).

When `apt-vim install <url>` is executed, apt-vim first checks the cloned repo for a JSON with `@vimpkg` as the first line.  If a valid JSON is found, its configuration is used. Otherwise, perform a regular install with user prompts etc.

**Comment by marijnh** [comment]
Wonderful! Merged as dbc3ea1

**Pull request closed without merging**
